# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(400, 382)
        self.verticalLayout = QtWidgets.QVBoxLayout(Loading)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingFrame = QtWidgets.QFrame(Loading)
        self.loadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadingFrame.setObjectName("loadingFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loadingFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.anim = QtWidgets.QLabel(self.loadingFrame)
        self.anim.setMinimumSize(QtCore.QSize(100, 100))
        self.anim.setText("")
        self.anim.setAlignment(QtCore.Qt.AlignCenter)
        self.anim.setObjectName("anim")
        self.verticalLayout_2.addWidget(self.anim)
        self.label = QtWidgets.QLabel(self.loadingFrame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFFFFF;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.loadingFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", "Form"))
        self.label.setText(_translate("Loading", "Loading..."))
