# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ui/ui_sources/resources', 'ui/ui_sources/resources'),
        ('libs', 'libs'),
        ('tools', 'tools'),
        ('splash.png', '.'),
        ('file_icon.ico', '.'),
        ('license.txt', '.'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui', 
        'PySide6.QtWidgets',
        'core.core.controller.controller',
        'core.core.worker.modloader',
        'core.core.worker.brawlhalla',
        'core.core.worker.gamefiles',
        'core.core.worker.gameswf',
        'core.core.worker.bnkhandler',
        'core.core.worker.langbin',
        'core.core.worker.mod',
        'core.core.worker.dispatch',
        'core.core.worker.async_mod_loader',
        'core.core.worker.basedispatch',
        'core.core.worker.basemod',
        'core.core.worker.config',
        'core.core.worker.dataversion',
        'core.core.worker.exceptions',
        'core.core.worker.variables',
        'core.core.worker.vartypes',
        'core.core.commands',
        'core.core.notifications',
        'core.core.windows',
        'core.core.swf.swf',
        'core.core.swf.bytearray',
        'core.core.swf.constants',
        'core.core.swf.metadataclass',
        'core.core.swf.symbolclass',
        'core.core.utils.bytes',
        'core.core.utils.hash',
        'core.core.ffdec.classes',
        'ui.ui_handler.window',
        'ui.ui_handler.mods',
        'ui.ui_handler.loading',
        'ui.ui_handler.modbutton',
        'ui.ui_handler.modclass',
        'ui.ui_handler.acceptdialog',
        'ui.ui_handler.buttonsdialog',
        'ui.ui_handler.progressdialog',
        'ui.ui_handler.header',
        'ui.ui_sources.ui_window',
        'ui.ui_sources.ui_mods',
        'ui.ui_sources.ui_loading',
        'ui.ui_sources.ui_mod_button',
        'ui.ui_sources.ui_mod_body',
        'ui.ui_sources.ui_mods_actions',
        'ui.ui_sources.ui_accept_dialog',
        'ui.ui_sources.ui_buttons_dialog',
        'ui.ui_sources.ui_progress_dialog',
        'ui.ui_sources.ui_header',
        'ui.ui_sources.icons_rc',
        'ui.ui_sources.translate',
        'ui.utils.buttongroup',
        'ui.utils.buttons',
        'ui.utils.layout',
        'ui.utils.mainthread',
        'ui.utils.systemdialog',
        'ui.utils.textformater',
        'ui.utils.version',
        'ui.utils.widget',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Brawlhalla Mod Loader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='file_icon.ico',
)







